language: go
go: 
 - 1.5.4
 - 1.6.3
 - 1.7.3
 - tip

go_import_path: github.com/mroote/factorio-server-manager/src

install:
  - go get github.com/apexskier/httpauth
  - go get github.com/go-ini/ini
  - go get github.com/gorilla/mux
  - go get github.com/hpcloud/tail
  - go get github.com/gorilla/websocket
  - go get github.com/majormjr/rcon

script:
 - go test -v ./...
